package com.ipd.taxiu.bean;

import java.util.List;

public class StoreSecondIndexResultBean {


    public List<BannerBean> BANNER_LIST;
    public List<StoreIndexCategoryBean> TYPE_LIST;
    public List<PRODUCTLISTBeanX> PRODUCT_LIST;
    public List<StoreVideoBean> VIDEO_LIST;


    public static class PRODUCTLISTBeanX {
        /**
         * TYPE_DATA : {"TYPE_ID":1,"TYPE_NAME":"狗粮","CATEGORY":1,"ICON":"/upload/shop/icon1.png","LOGO":"upload/default/dog.png","PIC":"/upload/shop/pic.png","KIND":0,"BRAND_IDS":"1,2,3,4,5,6,7,8","CONTENT":"","URL":"","PRODUCT_ID":0,"SORT":0,"CREATETIME":"2018-08-24 16:10:05","STATUS":1,"BRAND_LIST":[{"BRAND_ID":1,"BRAND_NAME":"冠能","LOGO":"/upload/image/20180819/brand.png","IS_RECOMMEND":0,"SORT":0,"CREATETIME":"","STATUS":0},{"BRAND_ID":2,"BRAND_NAME":"贵族","LOGO":"/upload/image/20180819/brand2.png","IS_RECOMMEND":0,"SORT":0,"CREATETIME":"","STATUS":0},{"BRAND_ID":3,"BRAND_NAME":"N3","LOGO":"/upload/image/20180819/brand.png","IS_RECOMMEND":0,"SORT":0,"CREATETIME":"","STATUS":0},{"BRAND_ID":4,"BRAND_NAME":"耐吉斯","LOGO":"/upload/image/20180819/brand2.png","IS_RECOMMEND":0,"SORT":0,"CREATETIME":"","STATUS":0},{"BRAND_ID":5,"BRAND_NAME":"鱼子酱","LOGO":"/upload/image/20180819/brand2.png","IS_RECOMMEND":0,"SORT":0,"CREATETIME":"","STATUS":0},{"BRAND_ID":6,"BRAND_NAME":"路斯","LOGO":"/upload/image/20180819/brand.png","IS_RECOMMEND":0,"SORT":0,"CREATETIME":"","STATUS":0},{"BRAND_ID":7,"BRAND_NAME":"宝路","LOGO":"/upload/image/20180819/brand.png","IS_RECOMMEND":0,"SORT":0,"CREATETIME":"","STATUS":0},{"BRAND_ID":8,"BRAND_NAME":"PET Baby","LOGO":"/upload/image/20180819/brand2.png","IS_RECOMMEND":0,"SORT":0,"CREATETIME":"","STATUS":0}],"PRODUCT_LIST":[{"PRODUCT_ID":13,"PROCUCT_NAME":"奶糕13","PRODUCT_NUMBER":"00000000013","BRAND":"贵族","LOGO":"/upload/shop/pro.png","FORM_ID":16,"NET_CONTENT":1,"PRICE":10,"REFER_PRICE":20,"DEAL_PRICE":0,"FORM_GROUP_PRICE":10},{"PRODUCT_ID":12,"PROCUCT_NAME":"奶糕12","PRODUCT_NUMBER":"00000000012","BRAND":"冠能","LOGO":"/upload/shop/pro.png","FORM_ID":15,"NET_CONTENT":1.5,"PRICE":10,"REFER_PRICE":20,"DEAL_PRICE":0,"FORM_GROUP_PRICE":10},{"PRODUCT_ID":11,"PROCUCT_NAME":"奶糕11","PRODUCT_NUMBER":"00000000011","BRAND":"贵族","LOGO":"/upload/shop/pro.png","FORM_ID":14,"NET_CONTENT":1.5,"PRICE":10,"REFER_PRICE":20,"DEAL_PRICE":0,"FORM_GROUP_PRICE":10},{"PRODUCT_ID":10,"PROCUCT_NAME":"奶糕10","PRODUCT_NUMBER":"00000000010","BRAND":"冠能","LOGO":"/upload/shop/pro.png","FORM_ID":13,"NET_CONTENT":1.5,"PRICE":10,"REFER_PRICE":20,"DEAL_PRICE":0,"FORM_GROUP_PRICE":10},{"PRODUCT_ID":9,"PROCUCT_NAME":"奶糕9","PRODUCT_NUMBER":"00000000009","BRAND":"贵族","LOGO":"/upload/shop/pro.png","FORM_ID":12,"NET_CONTENT":1.5,"PRICE":10,"REFER_PRICE":20,"DEAL_PRICE":0,"FORM_GROUP_PRICE":10},{"PRODUCT_ID":8,"PROCUCT_NAME":"奶糕8","PRODUCT_NUMBER":"00000000008","BRAND":"冠能","LOGO":"/upload/shop/pro.png","FORM_ID":11,"NET_CONTENT":1.5,"PRICE":10,"REFER_PRICE":20,"DEAL_PRICE":0,"FORM_GROUP_PRICE":10},{"PRODUCT_ID":7,"PROCUCT_NAME":"奶糕7","PRODUCT_NUMBER":"00000000007","BRAND":"冠能","LOGO":"/upload/shop/pro.png","FORM_ID":10,"NET_CONTENT":1.5,"PRICE":10,"REFER_PRICE":20,"DEAL_PRICE":0,"FORM_GROUP_PRICE":10},{"PRODUCT_ID":6,"PROCUCT_NAME":"奶糕6","PRODUCT_NUMBER":"00000000006","BRAND":"冠能","LOGO":"/upload/shop/pro.png","FORM_ID":9,"NET_CONTENT":1.5,"PRICE":10,"REFER_PRICE":20,"DEAL_PRICE":0,"FORM_GROUP_PRICE":10},{"PRODUCT_ID":5,"PROCUCT_NAME":"奶糕5","PRODUCT_NUMBER":"00000000005","BRAND":"冠能","LOGO":"/upload/shop/pro.png","FORM_ID":8,"NET_CONTENT":1.5,"PRICE":10,"REFER_PRICE":20,"DEAL_PRICE":0,"FORM_GROUP_PRICE":10},{"PRODUCT_ID":4,"PROCUCT_NAME":"奶糕4","PRODUCT_NUMBER":"00000000004","BRAND":"贵族","LOGO":"/upload/shop/pro.png","FORM_ID":7,"NET_CONTENT":1.5,"PRICE":10,"REFER_PRICE":20,"DEAL_PRICE":0,"FORM_GROUP_PRICE":10}]}
         */

        public StoreIndexSpecialBean TYPE_DATA;

    }
}
