/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ipd_ffmpeg_FFmpegApi */

#ifndef _Included_com_ipd_ffmpeg_FFmpegApi
#define _Included_com_ipd_ffmpeg_FFmpegApi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ipd_ffmpeg_FFmpegApi
 * Method:    exec
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_ipd_ffmpeg_FFmpegApi_exec
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
